# Generated by Django 3.0.5 on 2020-05-10 15:34

import articles.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_comment_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Artykuł', 'verbose_name_plural': 'Artykuły'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='Tytuł w pasku adresowym'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp',
            field=articles.models.CustomDateTimeField(auto_now_add=True, verbose_name='Czas utworzenia'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='Artykuł'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=articles.models.CustomDateTimeField(auto_now_add=True, verbose_name='Czas utworzenia'),
        ),
    ]
