# Generated by Django 3.0.5 on 2020-05-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200510_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Reakcja', 'verbose_name_plural': 'Reakcje'},
        ),
    ]
